export let glassesArray = [
  {
    id: 1,
    price: 30,
    name: "GUCCI G8850U",
    url: "./glasses/glassesImage/v1.png",
    thumbnail: "./glasses/glassesImage/g1.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
  {
    id: 2,
    price: 50,
    name: "GUCCI G8759H",
    url: "./glasses/glassesImage/v2.png",
    thumbnail: "./glasses/glassesImage/g2.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
  {
    id: 3,
    price: 30,
    name: "DIOR D6700HQ",
    url: "./glasses/glassesImage/v3.png",
    thumbnail: "./glasses/glassesImage/g3.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
  {
    id: 4,
    price: 70,
    name: "DIOR D6005U",
    url: "./glasses/glassesImage/v4.png",
    thumbnail: "./glasses/glassesImage/g4.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
  {
    id: 5,
    price: 40,
    name: "PRADA P8750",
    url: "./glasses/glassesImage/v5.png",
    thumbnail: "./glasses/glassesImage/g5.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
  {
    id: 6,
    price: 60,
    name: "PRADA P9700",
    url: "./glasses/glassesImage/v6.png",
    thumbnail: "./glasses/glassesImage/g6.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
  {
    id: 7,
    price: 80,
    name: "FENDI F8750",
    url: "./glasses/glassesImage/v7.png",
    thumbnail: "./glasses/glassesImage/g7.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
  {
    id: 8,
    price: 100,
    name: "FENDI F8500",
    url: "./glasses/glassesImage/v8.png",
    thumbnail: "./glasses/glassesImage/g8.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
  {
    id: 9,
    price: 60,
    name: "FENDI F4300",
    url: "./glasses/glassesImage/v9.png",
    thumbnail: "./glasses/glassesImage/g9.jpg",
    desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
  },
];
